# ==============================================================================
# AWS EC2 환경 대상 인벤토리 설정
# ==============================================================================

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# ==========================================
# RedHat 계열 (Amazon Linux 2023, Fedora, RHEL, Rocky, CentOS)
# ==========================================
[amazon_linux]
ec2-al2023-01 ansible_host=10.10.13.45 ansible_user=ec2-user

[fedora]

[rhel]

[rocky]

[centos]

[redhat_family:children]
amazon_linux
fedora
rhel
rocky
centos

# ==========================================
# Debian 계열 (Ubuntu, Debian)
# ==========================================
[ubuntu]

[debian]

[debian_family:children]
ubuntu
debian

# ==========================================
# BSD 계열 (FreeBSD)
# ==========================================
[freebsd]

[linux_servers:children]
redhat_family
debian_family

[target_servers:children]
linux_servers
freebsd
