---
# roles/kisa_audit/defaults/main.yml
audit_report_dest: "./reports/kisa_audit_report_{{ inventory_hostname }}_{{ ansible_date_time.date | default('latest') }}.md"
kisa_script_path: "/tmp/vulnerability_check_sh.sh"
